<?php
//echo '<pre>'.print_r($page,1).'</pre>';
?>
<hgroup>
    <?php echo $page->title ? '<h2>'.TITLE.'</h2> / <h1>'. $page->title.'</h1>' : '<h1>'.TITLE.'</h1>'; ?>
</hgroup>
<?php if(!$page->layout || $page->layout == 'single'):?>
<h2 class="none"><?php echo $page->description; ?></h2>
<?php echo $page->content; ?>
<?php else:?>
<div id="aside" class="<?php echo $page->layout; ?>">
    <menu>
        <?php foreach ($page->subpages as $k=>$i):?> 
        <a href="/<?php echo PAGE; ?>/<?php echo $k; ?>" <?php echo $k==$param?'class="selected"':''; ?>><?php echo $i; ?></a>
        <?php endforeach;?>
    </menu>
</div>
<div id="content">
    <h2 class="none"><?php echo $page->description; ?></h2>
    <?php echo $page->content; ?>
</div>
<?php endif;?>
<div class="clearfix"></div>
<script src="//<?php echo COOKIELESS; ?>/lib/js/ubox.js"></script>
<script>
    $().ready(function(){
        $('#page .thumb').ubox({
            loader  :'/themes/'+ THEME +'/images/loader.gif',
            previous:'/themes/'+ THEME +'/images/ubox-sprite.png',
            next    :'/themes/'+ THEME +'/images/ubox-sprite.png',
            close   :'/themes/'+ THEME +'/images/ubox-sprite.png'
        })
    });
</script>